apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlflow.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
     {{- include "mlflow.selectorLabels" . | nindent 4 }}
data:
  BACKEND_STORE_URI: {{ .Values.backendStoreURI }}
{{- if not .Values.objectBucketClaim.enabled }}
  DEFAULT_ARTIFACT_ROOT: {{ .Values.defaultArtifactRoot }}
{{- end }}