{{- if .Values.objectBucketClaim.enabled }}
apiVersion: objectbucket.io/v1alpha1
kind: ObjectBucketClaim
metadata:
  name: {{ include "mlflow.fullname" . }}-obc
  labels:
    app: noobaa
    bucket-provisioner: openshift-storage.noobaa.io-obc
    noobaa-domain: openshift-storage.noobaa.io
spec:
  additionalConfig:
    bucketclass: noobaa-default-bucket-class
  generateBucketName: {{ include "mlflow.fullname" . }}-obc
  storageClassName: openshift-storage.noobaa.io
{{- end }}